[tool.ruff]
line-length = 100
target-version = "py311"
fix = true

[tool.ruff.lint]
extend-select = ["E","F","I","B","UP"]

[tool.ruff.lint.isort]
known-first-party = ["app"]

[tool.ruff.format]
quote-style = "double"

[tool.mypy]
python_version = "3.11"
packages = ["app"]
strict = true
