name: ci
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: pip install -r requirements.txt -r requirements-dev.txt
      - name: Lint & format
        run: ruff check . && ruff format --check .
      - name: Types
        run: mypy app
      - name: Tests (coverage gate)
        run: pytest -q --cov=app --cov-fail-under=75
      - name: Security (SAST & deps)
        run: pip install bandit pip-audit && bandit -r app && pip-audit --strict
