name: test-checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  simple-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Test check working"
